'use server'

import { adminDb, adminAuth } from "@/firebase/admin";
import { cookies } from "next/headers";

/**
 * ==========================================
 * SYNC USER ACCOUNT TO FIRESTORE
 * ==========================================
 * Following a successful Firebase Auth registration (whether natively or via Google), 
 * this Server Action creates or updates the user's permanent database record in Firestore.
 * 
 * @param params Contains the user's secure UID, and optionally their Name, Email, and Avatar Photo.
 */
export async function signUp(params: SignUpParams) {
    const { uid, name, email, photoURL } = params;
    
    try {
        // 1. Fetch existing user document to check if they already have an avatar
        const userRef = adminDb.collection("users").doc(uid);
        const userDoc = await userRef.get();

        // 2. We use `{ merge: true }` so that if a user logs in repeatedly with Google, 
        // we don't erase their original `createdAt` timestamp.
        const updateData: any = {
            name: name || userDoc.data()?.name || "",
            email: email || userDoc.data()?.email || "",
            ...( !userDoc.exists && { createdAt: new Date().toISOString() } ),
        };

        // 3. SILENT PRESERVATION: Only overwrite the photo if the user DOES NOT already have one!
        if (!userDoc.exists || !userDoc.data()?.photoURL) {
            updateData.photoURL = photoURL || "";
        }

        await userRef.set(updateData, { merge: true });

        return {
            success: true,
            message: "Account synced successfully."
        };
    } catch (e: any) {
        console.error("Error syncing user data to Firestore:", e);

        return {
            success: false,
            message: "Failed to sync account."
        }
    }
}

/**
 * ==========================================
 * RECORD USER SIGN-IN
 * ==========================================
 * Used to update the user's database record upon a successful login.
 * Useful for tracking actively used accounts by updating `lastLoginAt`.
 * 
 * @param uid The user's secure Firebase UID.
 */
export async function signIn(uid: string) {
    try {
        await adminDb.collection("users").doc(uid).set({
            lastLoginAt: new Date().toISOString()
        }, { merge: true });

        return {
            success: true,
            message: "Sign-in recorded successfully."
        };
    } catch (error) {
        console.error("Error recording sign-in:", error);
        return {
            success: false,
            message: "Failed to record sign-in."
        };
    }
}

/**
 * ==========================================
 * VERIFY USER EMAIL IDENTIFIER
 * ==========================================
 * Securely checks if an email is already registered in Firebase Auth without attempting to log in.
 */
export async function checkUserExists(email: string) {
    try {
        await adminAuth.getUserByEmail(email);
        return { 
            exists: true, 
            success: true 
        };
    } catch (error: any) {
        if (error.code === 'auth/user-not-found') {
            return { 
                exists: false, 
                success: false, 
                message: 'User does not exist. Create an account instead.' 
            };
        }
        return { exists: false, success: false, message: 'An error occurred during verification.' };
    }
}

/**
 * ==========================================
 * CREATE SECURE SERVER SESSION COOKIE
 * ==========================================
 * Used to keep the Next.js Server (Middlewares & Layouts) in sync with the Client's auth state.
 * Takes the raw Token generated by Firebase Client auth and trades it for a secure HttpOnly Session Cookie.
 * 
 * @param idToken The raw authentication token from `userCredential.user.getIdToken()`
 */
export async function setSessionCookie(idToken: string) {
    try {
        // Create session cookie to last for exactly 1 week (7 days)
        const expiresIn = 60 * 60 * 24 * 7 * 1000; 
        
        // 1. Ask Firebase Admin to verify the client token and mint a long-lived cookie response
        const sessionCookie = await adminAuth.createSessionCookie(idToken, { expiresIn });
        
        // 2. Set the newly minted cookie using the Next.js 15 Cookie API securely.
        const cookieStore = await cookies();
        cookieStore.set('session', sessionCookie, {
            maxAge: expiresIn / 1000, // Cookie maxAge expects seconds, not milliseconds!
            httpOnly: true, // Crucial: Prevents JavaScript XSS attacks from reading the auth token!
            secure: process.env.NODE_ENV === 'production', // Only require HTTPS in real production environments
            path: '/', // Ensure the cookie is readable globally across the entire app
            sameSite: 'lax', // Protects against Cross-Site Request Forgery (CSRF) attacks
        });

        return { success: true };
    } catch (error) {
        console.error("Failed to create session cookie", error);
        return { success: false, message: "Authentication failed. Could not verify session server-side." };
    }
}

/**
 * ==========================================
 * DESTROY SERVER SESSION COOKIE
 * ==========================================
 * Logs the user out securely from the server perspective by nuking the 'session' cookie.
 */
export async function removeSession() {
    try {
        const cookieStore = await cookies();
        cookieStore.delete('session');
        return { success: true };
    } catch (error) {
        console.error("Failed to remove session cookie", error);
        return { success: false };
    }
}

/**
 * ==========================================
 * SECURELY FETCH CURRENT USER (SERVER ONLY)
 * ==========================================
 * Next.js Server Components call this to invisibly grab the user's data from Firestore 
 * using their HTTPOnly Session Cookie, absolutely completely preventing client-side loading screens!
 */
export async function getCurrentUser() {
    try {
        const cookieStore = await cookies();
        const sessionCookie = cookieStore.get('session')?.value;

        if (!sessionCookie) return null;

        // 1. Cryptographically verify the session is legit and hasn't been tampered with
        const decodedClaims = await adminAuth.verifySessionCookie(sessionCookie, true);

        // 2. Safely Fetch their live detailed profile from Firestore bypassing client-side security rules
        const userDoc = await adminDb.collection("users").doc(decodedClaims.uid).get();
        const data = userDoc.data();

        if (!userDoc.exists || !data) return null;

        // 3. Return strictly serializable data to prevent Next.js React hydration crashes
        return {
            uid: decodedClaims.uid,
            name: data.name || "User",
            email: data.email,
            photoURL: data.photoURL,
        };
    } catch (error) {
        // Normal behavior when session is expired or strictly doesn't exist
        return null;
    }
}

/**
 * ==========================================
 * BOOLEAN AUTH GUARD
 * ==========================================
 * Returns a simple true/false boolean designed specifically to rapidly block Next.js Layouts.
 * Exactly matches your tutor's architecture.
 */
export async function isAuthenticated() {
    const user = await getCurrentUser();
    return !!user;
}
